Update docker-entrypoint

diff --git a/scripts/docker-entrypoint b/scripts/docker-entrypoint
--- a/scripts/docker-entrypoint
+++ b/scripts/docker-entrypoint
@@ -85,14 +85,15 @@ if [ ! -e /tor-config-done ]; then
 	fi
 	echo -e "HiddenServicePort ${TOR_HS_PORT} ${TOR_HS_ADDR}:${TOR_HS_PORT}" >> /etc/tor/torrc
 	;;
-      *)
-        echo "Role variable missing"
-        exit 1
-        ;;
       DDOS)
   mkdir /ddos && \
   git clone https://github.com/r3nt0n/torDDoS.git && \
         ;;
+      *)
+        echo "Role variable missing"
+        exit 1
+        ;;
+     
       esac
 
     # Buffer to let the directory authority list be built
